# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.twitter:
        class:     AppBundle\Service\Twitter
        arguments: ['%twitter_consumer_key%', '%twitter_consumer_secret%']
